# STAMPARE A VIDEO / IMPRIMER A VIDEO
print('Hello world!!!')

# CONVERTIRE DA DECIMALE A INTERO / CONVERTIRE DE DECIMALE EN ENTIER
x = int(10.6)
print(x)

# CONVERTIRE DA INTERO A DECIMALE / CONVERTIRE DE ENTIER EN DECIMALE
x = float(10)
print(x)